
steps:
- uses: actions/checkout@v3
- uses: actions-for-kicad/setup-kicad@v1.0
  with:
    version: '7.0'
- uses: actions-for-kicad/generate-kicad-files@v1.0
  with:
    file: './mk1-rev0.2/bmc/bmc-unit.kicad_sch'
    type: 'schematic_pdf'
- name: Upload 
  uses: actions/upload-artifact@v3
  with:
    name: 'file.pdf'
    path: './file.pdf'

