name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      name:
        description: 'Workflow run name'
        required: false
        default: 'Manual test run'



jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: kibot-release.yaml
          dir: output
          verbose: 1
          schema: 'kicad/mk2/srvant-mk2/srvant-mk2.kicad_sch'
          board: 'kicad/mk2/srvant-mk2/srvant-mk2.kicad_pcb'
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output


